/* Integration loaded before multiplayer captures the engine hooks. */
(() => {
  'use strict';
  const T=window.TabokTreasure,oldNewState=newState,oldCollect=collectEquipment,oldRenderPlayers=renderPlayers,oldEquipment=renderEquipment,oldCross=cross,oldKill=kill,oldRune=applyCanonicalRune;
  const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  TREASURES.splice(0,3,{name:T.COMMONS[0],short:'S',cls:'relic'},{name:T.COMMONS[1],short:'M',cls:'oddity'},{name:'Artifacts',short:'A',cls:'keepsake'});
  function ring(q,r){const a=[];for(let i=0;i<6;i++){a.push(key(q,r+11));[q,r]=[-r,q+r]}return a}
  function sites(){const used=new Set([...RUNE_SITES,...JUDGE_SITES,...entries]);return [...ring(0,-7),...ring(0,-5),...ring(2,-5)].map(pos=>{if(!playable.has(pos)||used.has(pos))pos=[...playable].filter(x=>!used.has(x)).sort((a,b)=>boardDistance(a,pos)-boardDistance(b,pos))[0];used.add(pos);return pos})}
  newState=function(...args){const state=oldNewState(...args),positions=sites();let last=null;try{last=localStorage.getItem('tabok-last-riddle')}catch(_){}const setup=T.expedition(window.TabokRiddles,positions.slice(0,6),Math.random,last);try{localStorage.setItem('tabok-last-riddle',setup.riddle.id)}catch(_){}
    state.rulesVersion='2.0.0-R1';state.crossing={...setup.riddle,riddle:setup.riddle.phrase,name:'THE RIDDLE CROSSING'};state.selectedArtifacts=setup.selected;state.boardTreasures=[...setup.items,...positions.slice(6).map((pos,i)=>({id:'common-'+i,kind:'common',common:i<6?0:1,name:T.COMMONS[i<6?0:1],pos,readyRound:1}))];state.awakeStatues=[];state.rejectedArtifacts=[];delete state.supply;state.players.forEach(p=>p.artifacts=[]);return state};
  const actorOccupied=hexOccupied;
  hexOccupied=function(id,exceptPlayer=null,exceptMonster=null){return actorOccupied(id,exceptPlayer,exceptMonster)||Boolean(game?.awakeStatues&&JUDGE_SITES.some((site,i)=>site===id&&!game.awakeStatues.includes(i+1)))};
  function respawnSites(){return [...playable].filter(id=>!hexOccupied(id)&&!game.runes.has(id))}
  function returnHeld(p){T.returnArtifacts(game,p,respawnSites());}
  function visibleItems(){return(game.boardTreasures||[]).filter(t=>t.pos&&(t.kind==='artifact'||t.readyRound<=game.round))}
  function clue(){return '<blockquote class="crossing-clue">'+escape(game.crossing.phrase)+'</blockquote><p class="crossing-cost">Bring <b>one artifact</b> that answers the riddle + <b>1 Sun Shard</b> + <b>1 Moon Pearl</b>.</p>'}
  showCrossingIntro=function(){game.phase='intro';renderAll();showMessage('A new expedition','THE RIDDLE CROSSING',clue()+'<p>Six artifacts await. Walk over treasures to collect them. Common sites refresh next round. Each pickup wakes the nearest sleeping Judge.</p>',()=>{game.phase='choose';addLog('Read the riddle. Gather two common treasures and an answer.');renderAll();scheduleRuinEvents()},false);els.messageContinue.textContent='Begin'};
  renderAccounting=function(){els.account.innerHTML='<div class="riddle-ledger">'+clue()+'<small>'+game.finishPlace+' Crossed · '+escape(game.crossing.difficulty)+' riddle · '+escape(game.crossing.id)+'</small></div>'};
  renderPlayers=function(){oldRenderPlayers();for(const p of game.players){const card=els.players.querySelector('[data-traveler-target="'+p.p+'"] .traveler-copy');if(!card)continue;let list=card.querySelector('.artifact-inventory');if(!list){list=document.createElement('div');list.className='artifact-inventory';card.appendChild(list)}list.textContent=p.artifacts?.length?p.artifacts.join(' · '):'No unique artifact'}};
  renderEquipment=function(){equipmentRenderKey='';oldEquipment();for(const t of visibleItems()){const g=svg('g',{class:'board-treasure',transform:spatialTransform(t.pos),'pointer-events':'none'},els.equipment);svg('circle',{r:17,fill:t.kind==='artifact'?'#704386':t.common?'#7197b5':'#b8984c',stroke:'#e4cc95'},g);const label=svg('text',{y:4,'text-anchor':'middle',fill:'#fff','font-size':10},g);label.textContent=t.kind==='artifact'?t.name.slice(0,3):t.common?'MOON':'SUN';const title=svg('title',{},g);title.textContent=t.name}};
  syncTrue3DBoard=function(){if(!game||!webglBoard?.isTrue3D)return;webglBoard.syncState({players:game.players.filter(p=>p.status==='active').map(p=>({id:p.p,pos:p.pos,start:p.start,charId:p.charId,color:p.color,active:p===active()&&game.phase!=='monster'})),monsters:game.monsters.map(m=>({id:m.id,pos:m.pos,major:m.major,empowered:m.empowered,statue:m.statue})),dormantJudges:game.dormantJudges,awakeStatues:game.awakeStatues,treasures:visibleItems(),riddle:game.crossing?.phrase,equipment:[],runes:[...game.runes],legal:[...document.querySelectorAll('.playable.legal')].map(n=>n.dataset.id),portalLegal:Boolean(document.querySelector('.portal-target')),turnColor:active()?.color||'#ac76d4'})};
  awakenDormantJudges=function(count,pos){const awakened=[];for(let n=0;n<count;n++){const candidates=JUDGE_SITES.map((site,i)=>({site,index:i+1,distance:boardDistance(site,pos)})).filter(x=>!game.awakeStatues.includes(x.index)).sort((a,b)=>a.distance-b.distance);const next=candidates[0];if(!next)break;
      // The sleeping sculpture owns its hex already. It becomes the moving actor in place.
      if(actorOccupied(next.site))break;game.awakeStatues.push(next.index);game.dormantJudges=6-game.awakeStatues.length;const m={id:'M'+next.index,pos:next.site,major:false,statue:next.index};game.monsters.push(m);awakened.push(m.id);syncTrue3DBoard();webglBoard?.activateJudge?.(m.id);
    }if(!game.dormantJudges&&!game.seventhAwake){const major=summonMajorMonster(pos,'The sixth treasure alarm sounds');if(major.spawned)awakened.push('THE SEVENTH')}return awakened};
  function pickup(p,item){if(!T.claim(game,p,item,game.turn))return false;webglBoard?.pickupBurst(p.p,'rune');actorReaction(p,'take',item.name);addLog(p.name+' collected '+item.name+'.');const woke=awakenDormantJudges(1,p.pos);if(woke.length)addLog(woke.join(', ')+' awakened by the treasure.');renderEquipment();renderPlayers();syncTrue3DBoard();return true}
  collectEquipment=async function(p){await oldCollect(p);for(const item of visibleItems().filter(t=>t.pos===p.pos))pickup(p,item)};
  function nearbyCommon(p){return visibleItems().filter(t=>t.kind==='common'&&(t.pos===p.pos||neighbors(p.pos).includes(t.pos))&&!hexOccupied(t.pos,p)&&!(game.turn.collectedSites||[]).includes(t.id))}
  function collectReach(p,item){const at=p.pos;if(!nearbyCommon(p).includes(item))return false;const proxy={...p,pos:item.pos};const result=T.claim(game,proxy,item,game.turn);if(result){addLog(p.name+' reached for '+item.name+' at '+item.pos+'.');const woke=awakenDormantJudges(1,at);if(woke.length)addLog(woke.join(', ')+' awakened by the treasure.');renderAll()}return result}
  finishMovement=async function(){if(busy)return;const p=active();clearLegal();if(game.turn.heistPending){game.turn.heistPending=false;game.phase='heist';renderAll();renderHeist();return}finishBoardTreasure(p)};
  function finishBoardTreasure(p){if(game.turn.treasure==='CHOOSE'&&nearbyCommon(p).length){game.phase='treasure';renderAll();return}if(game.turn.treasure==='CHOOSE')addLog('Treasure reach found no ready, unoccupied common site beside '+p.name+'.');continueAfterTreasure()}
  renderTreasureRewardControls=function(){const panel=document.createElement('div');panel.className='treasure-action-panel';panel.innerHTML='<h3>Treasure reach</h3><p>Collect one common treasure from your hex or an adjacent open hex.</p>';nearbyCommon(active()).forEach(t=>{const b=document.createElement('button');b.dataset.treasureSite=t.id;b.textContent=t.name+' · '+t.pos;b.onclick=()=>chooseTreasureReward(t.id);panel.appendChild(b)});presentDecisionPanel(panel,'BOARD TREASURE')};
  chooseTreasureReward=function(id){if(busy||game.phase!=='treasure')return;const choices=nearbyCommon(active()),item=choices.find(t=>t.id===id)||(active().controller==='cpu'?choices.sort((a,b)=>active().inventory[a.common]-active().inventory[b.common])[0]:null);if(item)collectReach(active(),item);hideDecisionPanel();continueAfterTreasure()};
  applyCanonicalRune=function(p,face){if(face==='HEIST'){game.turn.heistPending=true;addLog('HEIST: after moving, attempt to steal one unique artifact with a D20.')}else if(face==='FORTUNE'){const item=nearbyCommon(p).sort((a,b)=>p.inventory[a.common]-p.inventory[b.common])[0];if(item)collectReach(p,item);else addLog('FORTUNE found no ready common treasure within reach.')}else oldRune(p,face)};
  const oldDescription=runeResultDescription;
  runeResultDescription=function(face){return face==='HEIST'?'Choose a rival artifact. D20: 1–9 fail, 10 reroll, 11–20 steal.':face==='FORTUNE'?'Collect a nearby ready common treasure.':oldDescription(face)};
  function heistTargets(){return game.players.filter(p=>p!==active()&&p.status==='active').flatMap(p=>p.artifacts.map(name=>({p,name})))}
  function renderHeist(){hideDecisionPanel();const options=heistTargets();if(!options.length){addLog('No rival carries a unique artifact to steal.');finishBoardTreasure(active());return}if(active().controller==='cpu'){resolveHeist(options[0].p.p,options[0].name);return}const panel=document.createElement('div');panel.className='treasure-action-panel';panel.innerHTML='<h3>Heist</h3><p>Steal one artifact: D20 1–9 fails, 10 rerolls, 11–20 succeeds.</p>';for(const target of options){const b=document.createElement('button');b.dataset.heistTarget=target.p.p;b.dataset.artifact=target.name;b.textContent=target.name+' from '+target.p.name;b.onclick=()=>resolveHeist(target.p.p,target.name);panel.appendChild(b)}presentDecisionPanel(panel,'RUNE · HEIST')}
  async function resolveHeist(slot,name){
    if(busy||game.phase!=='heist')return;
    const choice=heistTargets().find(t=>t.p.p===slot&&t.name===name);if(!choice)return;
    busy=true;hideDecisionPanel();const p=active(),visible=!window.TabokCanViewTurnRoll||window.TabokCanViewTurnRoll(p);let result;
    els.turnRoll.className='turn-roll-overlay dice-picking'+(visible?'':' hidden');
    els.turnRollKicker.textContent='RUNE · HEIST';els.turnRollName.textContent=p.name;
    els.turnRollRole.textContent='Steal '+name+' from '+choice.p.name;
    els.turnRollStatus.textContent='D20: 1–9 fail · 10 reroll · 11–20 steal';
    do{
      const n=1+Math.floor(Math.random()*20),spec={label:'Offer',faces:Array.from({length:20},(_,i)=>i+1),result:n};
      result=T.heistResult(n);game.heistRoll={phase:'roll',selected:['Offer'],specs:[spec]};
      window.TabokDiceSelection.mount(els.turnRollDice,els.turnRollControl,['Offer'],()=>{},()=>{},['Offer'],{renderer:visible?dice3D:null});
      renderAll();
      await window.TabokDiceSelection.roll(els.turnRollDice,els.turnRollControl,[spec]);
      addLog(p.name+' rolled '+n+' for Heist: '+result+'.');
    }while(result==='reroll');
    if(result==='success'&&T.transferArtifact(choice.p,p,name))addLog(p.name+' stole '+name+' from '+choice.p.name+'.');
    delete game.heistRoll;els.turnRoll.className='turn-roll-overlay hidden';dice3D?.hide();
    busy=false;finishBoardTreasure(p);
  }
  resolvePortal=function(p,gate){hideDecisionPanel();game.phase='portal';game.pendingPortal={p,gate};const submit=name=>judgeArtifact(p,gate,name);if(p.controller==='cpu'){const order=T.guesses(game.crossing.phrase,game.selectedArtifacts,game.rejectedArtifacts);submit(order.find(n=>p.artifacts.includes(n))||p.artifacts[0]||'');return}
    showMessage('Portal offering','Choose your answer',clue()+'<div id="artifactAnswers"></div><p>Choose one carried artifact. A wrong answer sends you back; it does not awaken a statue.</p>',()=>submit(''),false);const host=document.getElementById('artifactAnswers');p.artifacts.forEach(name=>{const b=document.createElement('button');b.dataset.portalArtifact=name;b.textContent=name;b.onclick=()=>{els.message.classList.add('hidden');pauseAmbient(false);submit(name)};host.appendChild(b)});els.messageContinue.textContent=p.artifacts.length?'Leave without an answer':'Continue'};
  function judgeArtifact(p,gate,name){if(game.phase!=='portal'||game.pendingPortal?.p!==p)return;const success=T.verdict(p,game.crossing,name);game.pendingPortal={p,gate,success,artifact:name};if(!success&&name&&!game.crossing.accepted.includes(name)&&!game.rejectedArtifacts.includes(name))game.rejectedArtifacts.push(name);showMessage('Portal judgment',success?'The riddle accepts your answer':'The offering is incomplete',clue()+'<p>'+escape(name||'No artifact')+' · Sun '+p.inventory[0]+' · Moon '+p.inventory[1]+'</p>',finalizeBalancePortal,p.controller==='cpu')}
  finalizeBalancePortal=function(){const q=game.pendingPortal;if(!q)return;game.pendingPortal=null;if(q.success){q.p.inventory[0]--;q.p.inventory[1]--;cross(q.p,'The Riddle Crossing');playCrossingAnimation(q.p,finishPlayerTurn)}else{game.rejections++;reject(q.p);waitForPortalVisuals(()=>showMessage('Portal rejection','The Portal refuses the offering','<p>Your treasures remain with you. Find another answer or the missing common treasures.</p>',finishPlayerTurn,true))}};
  cross=function(p,source){returnHeld(p);p.inventory=[0,0,0];oldCross(p,source)};
  kill=function(p,events){returnHeld(p);oldKill(p,events);events[events.length-1]=p.name+' is DNF; unique artifacts return to the board.'};
  const endRound=endMonsterPhase;endMonsterPhase=function(){T.retryRespawns(game,respawnSites());endRound()};
  renderOfferControls=function(){const p=active(),panel=document.createElement('div');panel.className='treasure-action-panel';panel.innerHTML='<h3>Offer '+game.turn.offerRemaining+' treasure(s)</h3>';const items=[...p.inventory.slice(0,2).flatMap((n,i)=>n?[{name:T.COMMONS[i],type:i}]:[]),...p.artifacts.map(name=>({name,type:2}))];for(const item of items){for(const target of [null,...(game.offerTargetMode==='random'?offerRecipients(p).slice(0,1):offerRecipients(p))]){const b=document.createElement('button');b.dataset.offerType=String(item.type);b.dataset.artifact=item.type===2?item.name:'';b.dataset.offerTarget=target?.p||'';b.dataset.offerDiscard=target?'0':'1';b.textContent=item.name+' → '+(target?(game.offerTargetMode==='random'?'random Traveler':target.name):'return / discard');b.onclick=()=>offerTreasure(item.type,target,!target,item.name);panel.appendChild(b)}}presentDecisionPanel(panel,'OFFERING')};
  offerTreasure=async function(type,target,discard=false,name){const p=active();if(busy||game.phase!=='offer'||![0,1,2].includes(type)||!p.inventory[type]||(!discard&&(!target||target===p||target.status!=='active')))return;if(!discard&&game.offerTargetMode==='random'){const recipients=offerRecipients(p);target=recipients[Math.floor(Math.random()*recipients.length)];if(!target)return}if(type===2){name=name||p.artifacts[0];if(!p.artifacts.includes(name))return;if(discard){const holder={artifacts:[name],inventory:[0,0,1]};returnHeld(holder);p.artifacts.splice(p.artifacts.indexOf(name),1);p.inventory[2]=p.artifacts.length}else T.transferArtifact(p,target,name)}else{p.inventory[type]--;if(!discard)target.inventory[type]++}addLog(p.name+' offered '+(name||TREASURES[type].name)+(discard?' back to the ruins.':' to '+target.name+'.'));hideDecisionPanel();game.turn.offerRemaining--;if(game.turn.offerRemaining>0&&p.inventory.some(Boolean))renderAll();else finishOffering()};
  aiHeadsPortal=function(p){return p.inventory[0]>0&&p.inventory[1]>0&&p.artifacts.some(n=>!game.rejectedArtifacts.includes(n))};
  chooseAIGoal=function(p){if(aiHeadsPortal(p))return 'PORTAL';const ranked=T.guesses(game.crossing.phrase,game.selectedArtifacts,game.rejectedArtifacts),distances=aiDistances(p,p.pos);const choices=visibleItems().filter(t=>t.kind==='artifact'?!p.artifacts.length||!p.artifacts.some(n=>!game.rejectedArtifacts.includes(n)):p.inventory[t.common]<1).map(t=>({t,score:(distances.get(t.pos)??999)+(t.kind==='artifact'?Math.max(0,ranked.indexOf(t.name))*2:0)})).filter(x=>x.score<900).sort((a,b)=>a.score-b.score);if(choices.length)return choices[0].t.pos;const rune=nearestAIRune(p);return rune?.position||[...playable].find(x=>distances.has(x)&&x!==p.pos)||p.pos};
  chooseCPUDice=function(p){const chosen=['Movement','Treasure'];if(p.rune)chosen.push('Rune');return chosen};
  const guidance=renderRollGuidance;renderRollGuidance=function(){guidance();if(game?.turn?.treasure==='CHOOSE')els.guidance.innerHTML=els.guidance.innerHTML.replace(/after moving, choose the Relic, Oddity, or Keepsake your pattern needs\./g,'after moving, reach for one ready common treasure on an adjacent open hex.')};
  // Retire old pool-only entry points even if a stale UI command arrives.
  take=function(){};steal=function(){};give=function(){};resolveRunePlunder=function(){};
})();
