const test=require('node:test'),assert=require('node:assert/strict');
const T=require('../treasure-rules.js'),library=require('../riddle-library.js');
const player=()=>({inventory:[0,0,0],artifacts:[],pos:'0,0'});
test('all 1200 original riddles have stable IDs, 1–3 valid answers and the intended difficulty mix',()=>{
 assert.equal(library.length,1200);assert.equal(new Set(library.map(r=>r.id)).size,1200);assert.equal(new Set(library.map(r=>r.phrase)).size,1200);
 for(const name of T.ARTIFACTS){const rows=library.filter(r=>r.artifact===name);assert.equal(rows.length,100);for(const [d,n]of [['Hard',75],['Medium',20],['Easy',5]])assert.equal(rows.filter(r=>r.difficulty===d).length,n)}
 for(const r of library){assert.ok(r.accepted.length>=1&&r.accepted.length<=3);assert.equal(new Set(r.accepted).size,r.accepted.length);assert.ok(r.accepted.includes(r.artifact));r.accepted.forEach(n=>assert.ok(T.ARTIFACTS.includes(n)))}
});
test('every riddle can generate exactly six unique artifacts with all accepted answers included',()=>{
 for(const r of library){const s=T.expedition([r],['a','b','c','d','e','f'],()=>.42);assert.equal(new Set(s.selected).size,6);r.accepted.forEach(a=>assert.ok(s.selected.includes(a)));assert.equal(new Set(s.items.map(i=>i.pos)).size,6)}
});
test('one accepted artifact plus both commons crosses, extra accepted artifacts are not required',()=>{
 for(const r of library)for(const a of r.accepted){const p={inventory:[1,1,1],artifacts:[a]};assert.equal(T.verdict(p,r,a),true);assert.equal(T.verdict({...p,inventory:[0,1,1]},r,a),false);assert.equal(T.verdict({...p,artifacts:[]},r,a),false);assert.equal(T.verdict(p,r,'Invalid'),false)}
});
test('D20 Heist preserves all twenty outcomes, including an explicit reroll',()=>{assert.equal(T.heistResult(1),'fail');assert.equal(T.heistResult(9),'fail');assert.equal(T.heistResult(10),'reroll');assert.equal(T.heistResult(11),'success');assert.equal(T.heistResult(20),'success');assert.throws(()=>T.heistResult(21));assert.equal(Array.from({length:20},(_,i)=>T.heistResult(i+1)).filter(x=>x==='success').length,10)});
test('common sites refresh next round and cannot be farmed in the same turn',()=>{const p=player(),item={id:'sun',kind:'common',common:0,pos:'0,0',readyRound:1},s={round:1,boardTreasures:[item]},turn={};assert.ok(T.claim(s,p,item,turn));assert.equal(p.inventory[0],1);assert.equal(T.claim(s,p,item,turn),false);assert.equal(T.claim(s,player(),item,{}),false);s.round=2;assert.ok(T.claim(s,p,item,{}));assert.equal(p.inventory[0],2)});
test('unique pickup, Heist, and return never duplicate or lose an artifact',()=>{const a=player(),b=player(),item={id:'Key',kind:'artifact',name:'Key',pos:'0,0'},s={boardTreasures:[item],round:1};assert.ok(T.claim(s,a,item,{}));assert.equal(item.pos,null);assert.equal(T.claim(s,b,item,{}),false);assert.ok(T.transferArtifact(a,b,'Key'));assert.equal(T.transferArtifact(a,b,'Key'),false);assert.deepEqual(a.artifacts,[]);assert.deepEqual(b.artifacts,['Key']);T.returnArtifacts(s,b,['1,0']);assert.equal(item.pos,'1,0');assert.deepEqual(b.inventory,[0,0,0]);assert.deepEqual(b.artifacts,[])});
test('blocked respawn waits and retries without deleting the unique artifact',()=>{const p={...player(),artifacts:['Key'],inventory:[0,0,1]},s={boardTreasures:[{id:'Key',name:'Key',kind:'artifact',pos:null}]};T.returnArtifacts(s,p,[]);assert.equal(s.boardTreasures[0].pendingRespawn,true);T.retryRespawns(s,['a']);assert.equal(s.boardTreasures[0].pos,'a');assert.equal(s.boardTreasures[0].pendingRespawn,undefined)});
test('CPU guesses use only clue words, visible identities and public failed guesses',()=>{assert.equal(T.guesses('My magnetic needle points north',['Key','Compass','Mask'])[0],'Compass');assert.deepEqual(T.guesses('My magnetic needle points north',['Key','Compass'],['Compass']),['Key']);const r={phrase:'A strange promise',accepted:['Seed']};assert.deepEqual(T.guesses(r.phrase,['Mask','Seed']),T.guesses('A strange promise',['Mask','Seed']))});
test('new game avoids the immediately previous riddle',()=>{const r=T.expedition(library,['a','b','c','d','e','f'],()=>0,library[0].id);assert.notEqual(r.riddle.id,library[0].id)});
